! This module contains intentionally failing assertions, and
! demonstrates the messages that are generated by failing asserts.

module test_failing
   use broken_sut_mod
   use funit

contains
   
   @test
   subroutine test_assert_true_and_false_fail()

      ! Intentionally failing test with an informative message:
      @assertTrue(1 == 2, message='intentionally failing test')

      ! WARNING: because of previous failure, the next assertion does
      ! not execute:
      @assertTrue('a' == 'b')

   end subroutine test_assert_true_and_false_fail

   @test
   subroutine test_assert_equal_fail()
      real, parameter :: x_expected = 9.
      
      @assertEqual(x_expected, square(3.), tolerance=0.0001, message='intentionally failing test')

   end subroutine test_assert_equal_fail

   @test
   subroutine test_fail_array()

      @assertEqual([1,4,9], square([1.,2.1,3.]), tolerance=0.1, message='intentionally failing test')
   end subroutine test_fail_array


end module test_failing
